### ISSUE TITLE
Indicate initial sort direction

### ISSUE THREAD

**Issue by joetime** [rdmurphy/tablesift.js#8]
Not _really_ an issue per se...
When I load my tables, there is usually one column that is already sorted. I'd like to indicate this to the user. 
Right now, I add the data-sort in my html:

``` html
<th data-sort='asc'>Column 1</th>
```

And add styling based on the data-sort (not the class):

``` css
/*placeholder - so the column width doesnt change during sort*/
table thead tr th.siftable::after
{
    content: ' ▲';
    color: transparent;
}

/*adds an up triangle to the asc sorted column*/
table thead tr th.siftable[data-sort=asc]::after,
table thead tr th.siftable.sift-init[data-sort=asc]::after {
    content: ' ▲';
    color: #006666;
}
/*adds a down triangle to the des sorted column*/
table thead tr th.siftable[data-sort=des]::after,
table thead tr th.siftable.sift-init[data-sort=des]::after {
    content: ' ▼';
    color: #006666;
}
```

This is kind of a hack, and there may be a better way to do this.This defeats the whole purpose of specifying the class.
Alternatively, we could add this method to the docs so people don't have to go through the trouble of solving the problem themselves.
